site_name: Xuan's Note
site_url: https://xuanzhizheng.github.io/NoteBook/

theme:
  name: 'material'
  default_light: true
  favicon: img/favicon.ico
  font: false
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default # 日间模式
      primary: blue grey  # 上方的
      accent: blue grey # 链接等可交互元件的高亮色
      # teal
      toggle:
        icon: material/toggle-switch # 图标
        name: 切换至夜间模式 # 鼠标悬浮提示
    - media: "(prefers-color-scheme: dark)"
      scheme: slate # 夜间模式
      primary: black
      accent: blue # 链接等可交互元件的高亮色
      # teal
      toggle:
        icon: material/toggle-switch-off-outline
        name: 切换至夜间模式
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
    - navigation.path
    - navigation.top
    - navigation.footer
    - search.suggest
    - search.highlight
    - content.code.copy

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - def_list
  # - mdx_truly_sane_lists
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight: # 代码块高亮
      auto_title: false # 显示编程语言名称
extra_javascript:
  - js/katex.js
  - js/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

extra_css:
  - https://cdn.tonycrane.cc/jbmono/jetbrainsmono.css
  - https://cdn.tonycrane.cc/lxgw/lxgwscreen.css
  - stylesheets/extra.css
  - https://unpkg.com/katex@0/dist/katex.min.css

plugins:
  - search
  - statistics
  - git-revision-date-localized:
      enable_creation_date: true

nav:
  - Home: index.md
  - IS: 
    - IS/index.md
    - Signal and System: 
      - 一、信号和系统的基本概念: IS/Signal_and_System1.md
      - 二、LTI系统的时域分析: IS/Signal_and_System2.md
  - EE: 
    - EE/index.md
    - Fundamentals of Electronic Circuits: EE/FoEC.md
  - Language:
    - Language/index.md
    - 한국어: Language/한국어.md
    - にほんご: Language/にほんご.md